### ISSUE TITLE
话说为啥弃用wurst改用lua了.

### ISSUE THREAD

**Issue by PhoenixZeng** [lhing17/juezhan#3]
虽然wurst坑一堆 不过至少还处于能用的状态吧?换成lua有什么重要的原因吗? 
(之所以这么问是因为我正在用wurst作图)
另外lua似乎很难调用dzapi吧 除非是内置

**Comment by lhing17** [comment]
> 虽然wurst坑一堆 不过至少还处于能用的状态吧?换成lua有什么重要的原因吗?
> (之所以这么问是因为我正在用wurst作图)
> 另外lua似乎很难调用dzapi吧 除非是内置

（1）之前用wurst是因为没了解过lua，在尝试过lua之后就不想用wurst了，因为wurst的语法是参考java的，比较啰嗦，感觉lua的table非常灵活，说白了还是个人喜好问题吧……
（2）在官方平台的环境下，dzapi是直接在japi中的，直接调用就可以了

**Comment by PhoenixZeng** [comment]
2 咦? 直接在japi包中吗? 也就是说
`local dz = require "jass.japi.dzapi" ` 或者`local dz = require "jass.japi" ` 就能直接调用dz相关的函数了? bzapi也是如此吗?(frame的那个)  在你的那个文件有啊?我去看看,我找了一圈没找到.
3 这个地图昨天玩了下感觉做的挺好的,就是有点复杂. 得抽个周末好好研究下

**Comment by lhing17** [comment]
> 2 咦? 直接在japi包中吗? 也就是说
> `local dz = require "jass.japi.dzapi" ` 或者`local dz = require "jass.japi" ` 就能直接调用dz相关的函数了? bzapi也是如此吗?(frame的那个) 在你的那个文件有啊?我去看看,我找了一圈没找到.
> 3 这个地图昨天玩了下感觉做的挺好的,就是有点复杂. 得抽个周末好好研究下

（1）直接`local dz = require "jass.japi" `就能调用了，包括dzapi和blzapi，acb的文档里有写，japi在不同环境下的列表是不同的，需要自己遍历去看。
（2）没看懂你说的frame指的是什么
（3）目前地图还是jass的版本，比较乱。正在往lua上迁移，迁移完可以简化和优化一部分功能。

**Comment by PhoenixZeng** [comment]
1,我不喜欢wurst主要是受到数组大小限制了对象数量,. 而且有时候还有奇怪的bug. lua的table很爽 但是语法还是不够讨喜.有些关键字很讨厌 比如then do之类的. 闭包也不舒服(更喜欢 ()-> )  这个确实是看个人. 
2,frame就是网易blzapi里面的一批主要界面函数吧..这个你怎么可能不知道..不过我的意思是我想看看你dz存档那一部分怎么写的

**Comment by PhoenixZeng** [comment]
thanks
